/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as InitiativesRouteImport } from './routes/initiatives'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/portal.profile'
import { Route as AuthenticatedPortalPodcastsRouteImport } from './routes/_authenticated/portal.podcasts'
import { Route as AuthenticatedPortalNewsRouteImport } from './routes/_authenticated/portal.news'
import { Route as AuthenticatedPortalMembershipRouteImport } from './routes/_authenticated/portal.membership'
import { Route as AuthenticatedPortalMagazineRouteImport } from './routes/_authenticated/portal.magazine'
import { Route as AuthenticatedPortalEventsRouteImport } from './routes/_authenticated/portal.events'
import { Route as AuthenticatedPortalAcademyRouteImport } from './routes/_authenticated/portal.academy'
import { Route as AuthenticatedAdminWebsiteRouteImport } from './routes/_authenticated/admin.website'
import { Route as AuthenticatedAdminTiersRouteImport } from './routes/_authenticated/admin.tiers'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPodcastsRouteImport } from './routes/_authenticated/admin.podcasts'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminMagazineRouteImport } from './routes/_authenticated/admin.magazine'
import { Route as AuthenticatedAdminLeadershipRouteImport } from './routes/_authenticated/admin.leadership'
import { Route as AuthenticatedAdminInitiativesRouteImport } from './routes/_authenticated/admin.initiatives'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminChaptersRouteImport } from './routes/_authenticated/admin.chapters'
import { Route as AuthenticatedAdminAcademyModulesRouteImport } from './routes/_authenticated/admin.academy-modules'
import { Route as AuthenticatedAdminAcademyRouteImport } from './routes/_authenticated/admin.academy'
import { Route as AuthenticatedAdminWebsiteIndexRouteImport } from './routes/_authenticated/admin.website.index'
import { Route as AuthenticatedPortalAcademySlugRouteImport } from './routes/_authenticated/portal.academy.$slug'
import { Route as AuthenticatedAdminWebsiteNavRouteImport } from './routes/_authenticated/admin.website.nav'
import { Route as AuthenticatedAdminWebsiteHeroRouteImport } from './routes/_authenticated/admin.website.hero'
import { Route as AuthenticatedAdminWebsiteGalleryRouteImport } from './routes/_authenticated/admin.website.gallery'
import { Route as AuthenticatedAdminWebsiteFooterRouteImport } from './routes/_authenticated/admin.website.footer'
import { Route as AuthenticatedAdminWebsiteFeaturedRouteImport } from './routes/_authenticated/admin.website.featured'
import { Route as AuthenticatedAdminWebsiteContactRouteImport } from './routes/_authenticated/admin.website.contact'
import { Route as AuthenticatedAdminWebsiteChaptersRouteImport } from './routes/_authenticated/admin.website.chapters'
import { Route as AuthenticatedAdminWebsiteBannerRouteImport } from './routes/_authenticated/admin.website.banner'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesRoute = InitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChaptersRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPodcastsRoute =
  AuthenticatedPortalPodcastsRouteImport.update({
    id: '/podcasts',
    path: '/podcasts',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalNewsRoute = AuthenticatedPortalNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedPortalMembershipRoute =
  AuthenticatedPortalMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMagazineRoute =
  AuthenticatedPortalMagazineRouteImport.update({
    id: '/magazine',
    path: '/magazine',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalEventsRoute =
  AuthenticatedPortalEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAcademyRoute =
  AuthenticatedPortalAcademyRouteImport.update({
    id: '/academy',
    path: '/academy',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminWebsiteRoute =
  AuthenticatedAdminWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTiersRoute = AuthenticatedAdminTiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPodcastsRoute =
  AuthenticatedAdminPodcastsRouteImport.update({
    id: '/podcasts',
    path: '/podcasts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMagazineRoute =
  AuthenticatedAdminMagazineRouteImport.update({
    id: '/magazine',
    path: '/magazine',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadershipRoute =
  AuthenticatedAdminLeadershipRouteImport.update({
    id: '/leadership',
    path: '/leadership',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInitiativesRoute =
  AuthenticatedAdminInitiativesRouteImport.update({
    id: '/initiatives',
    path: '/initiatives',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChaptersRoute =
  AuthenticatedAdminChaptersRouteImport.update({
    id: '/chapters',
    path: '/chapters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAcademyModulesRoute =
  AuthenticatedAdminAcademyModulesRouteImport.update({
    id: '/academy-modules',
    path: '/academy-modules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAcademyRoute =
  AuthenticatedAdminAcademyRouteImport.update({
    id: '/academy',
    path: '/academy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteIndexRoute =
  AuthenticatedAdminWebsiteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminWebsiteRoute,
  } as any)
const AuthenticatedPortalAcademySlugRoute =
  AuthenticatedPortalAcademySlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedPortalAcademyRoute,
  } as any)
const AuthenticatedAdminWebsiteNavRoute =
  AuthenticatedAdminWebsiteNavRouteImport.update({
    id: '/nav',
    path: '/nav',
    getParentRoute: () => AuthenticatedAdminWebsiteRoute,
  } as any)
const AuthenticatedAdminWebsiteHeroRoute =
  AuthenticatedAdminWebsiteHeroRouteImport.update({
    id: '/hero',
    path: '/hero',
    getParentRoute: () => AuthenticatedAdminWebsiteRoute,
  } as any)
const AuthenticatedAdminWebsiteGalleryRoute =
  AuthenticatedAdminWebsiteGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminWebsiteRoute,
  } as any)
const AuthenticatedAdminWebsiteFooterRoute =
  AuthenticatedAdminWebsiteFooterRouteImport.update({
    id: '/footer',
    path: '/footer',
    getParentRoute: () => AuthenticatedAdminWebsiteRoute,
  } as any)
const AuthenticatedAdminWebsiteFeaturedRoute =
  AuthenticatedAdminWebsiteFeaturedRouteImport.update({
    id: '/featured',
    path: '/featured',
    getParentRoute: () => AuthenticatedAdminWebsiteRoute,
  } as any)
const AuthenticatedAdminWebsiteContactRoute =
  AuthenticatedAdminWebsiteContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminWebsiteRoute,
  } as any)
const AuthenticatedAdminWebsiteChaptersRoute =
  AuthenticatedAdminWebsiteChaptersRouteImport.update({
    id: '/chapters',
    path: '/chapters',
    getParentRoute: () => AuthenticatedAdminWebsiteRoute,
  } as any)
const AuthenticatedAdminWebsiteBannerRoute =
  AuthenticatedAdminWebsiteBannerRouteImport.update({
    id: '/banner',
    path: '/banner',
    getParentRoute: () => AuthenticatedAdminWebsiteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/initiatives': typeof InitiativesRoute
  '/leadership': typeof LeadershipRoute
  '/magazine': typeof MagazineRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRoute
  '/podcasts': typeof PodcastsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/admin/academy': typeof AuthenticatedAdminAcademyRoute
  '/admin/academy-modules': typeof AuthenticatedAdminAcademyModulesRoute
  '/admin/chapters': typeof AuthenticatedAdminChaptersRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/initiatives': typeof AuthenticatedAdminInitiativesRoute
  '/admin/leadership': typeof AuthenticatedAdminLeadershipRoute
  '/admin/magazine': typeof AuthenticatedAdminMagazineRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/podcasts': typeof AuthenticatedAdminPodcastsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/tiers': typeof AuthenticatedAdminTiersRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRouteWithChildren
  '/portal/academy': typeof AuthenticatedPortalAcademyRouteWithChildren
  '/portal/events': typeof AuthenticatedPortalEventsRoute
  '/portal/magazine': typeof AuthenticatedPortalMagazineRoute
  '/portal/membership': typeof AuthenticatedPortalMembershipRoute
  '/portal/news': typeof AuthenticatedPortalNewsRoute
  '/portal/podcasts': typeof AuthenticatedPortalPodcastsRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/website/banner': typeof AuthenticatedAdminWebsiteBannerRoute
  '/admin/website/chapters': typeof AuthenticatedAdminWebsiteChaptersRoute
  '/admin/website/contact': typeof AuthenticatedAdminWebsiteContactRoute
  '/admin/website/featured': typeof AuthenticatedAdminWebsiteFeaturedRoute
  '/admin/website/footer': typeof AuthenticatedAdminWebsiteFooterRoute
  '/admin/website/gallery': typeof AuthenticatedAdminWebsiteGalleryRoute
  '/admin/website/hero': typeof AuthenticatedAdminWebsiteHeroRoute
  '/admin/website/nav': typeof AuthenticatedAdminWebsiteNavRoute
  '/portal/academy/$slug': typeof AuthenticatedPortalAcademySlugRoute
  '/admin/website/': typeof AuthenticatedAdminWebsiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/initiatives': typeof InitiativesRoute
  '/leadership': typeof LeadershipRoute
  '/magazine': typeof MagazineRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRoute
  '/podcasts': typeof PodcastsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/admin/academy': typeof AuthenticatedAdminAcademyRoute
  '/admin/academy-modules': typeof AuthenticatedAdminAcademyModulesRoute
  '/admin/chapters': typeof AuthenticatedAdminChaptersRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/initiatives': typeof AuthenticatedAdminInitiativesRoute
  '/admin/leadership': typeof AuthenticatedAdminLeadershipRoute
  '/admin/magazine': typeof AuthenticatedAdminMagazineRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/podcasts': typeof AuthenticatedAdminPodcastsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/tiers': typeof AuthenticatedAdminTiersRoute
  '/portal/academy': typeof AuthenticatedPortalAcademyRouteWithChildren
  '/portal/events': typeof AuthenticatedPortalEventsRoute
  '/portal/magazine': typeof AuthenticatedPortalMagazineRoute
  '/portal/membership': typeof AuthenticatedPortalMembershipRoute
  '/portal/news': typeof AuthenticatedPortalNewsRoute
  '/portal/podcasts': typeof AuthenticatedPortalPodcastsRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/website/banner': typeof AuthenticatedAdminWebsiteBannerRoute
  '/admin/website/chapters': typeof AuthenticatedAdminWebsiteChaptersRoute
  '/admin/website/contact': typeof AuthenticatedAdminWebsiteContactRoute
  '/admin/website/featured': typeof AuthenticatedAdminWebsiteFeaturedRoute
  '/admin/website/footer': typeof AuthenticatedAdminWebsiteFooterRoute
  '/admin/website/gallery': typeof AuthenticatedAdminWebsiteGalleryRoute
  '/admin/website/hero': typeof AuthenticatedAdminWebsiteHeroRoute
  '/admin/website/nav': typeof AuthenticatedAdminWebsiteNavRoute
  '/portal/academy/$slug': typeof AuthenticatedPortalAcademySlugRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/initiatives': typeof InitiativesRoute
  '/leadership': typeof LeadershipRoute
  '/magazine': typeof MagazineRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/partners': typeof PartnersRoute
  '/podcasts': typeof PodcastsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/_authenticated/admin/academy': typeof AuthenticatedAdminAcademyRoute
  '/_authenticated/admin/academy-modules': typeof AuthenticatedAdminAcademyModulesRoute
  '/_authenticated/admin/chapters': typeof AuthenticatedAdminChaptersRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/initiatives': typeof AuthenticatedAdminInitiativesRoute
  '/_authenticated/admin/leadership': typeof AuthenticatedAdminLeadershipRoute
  '/_authenticated/admin/magazine': typeof AuthenticatedAdminMagazineRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/podcasts': typeof AuthenticatedAdminPodcastsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/tiers': typeof AuthenticatedAdminTiersRoute
  '/_authenticated/admin/website': typeof AuthenticatedAdminWebsiteRouteWithChildren
  '/_authenticated/portal/academy': typeof AuthenticatedPortalAcademyRouteWithChildren
  '/_authenticated/portal/events': typeof AuthenticatedPortalEventsRoute
  '/_authenticated/portal/magazine': typeof AuthenticatedPortalMagazineRoute
  '/_authenticated/portal/membership': typeof AuthenticatedPortalMembershipRoute
  '/_authenticated/portal/news': typeof AuthenticatedPortalNewsRoute
  '/_authenticated/portal/podcasts': typeof AuthenticatedPortalPodcastsRoute
  '/_authenticated/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/website/banner': typeof AuthenticatedAdminWebsiteBannerRoute
  '/_authenticated/admin/website/chapters': typeof AuthenticatedAdminWebsiteChaptersRoute
  '/_authenticated/admin/website/contact': typeof AuthenticatedAdminWebsiteContactRoute
  '/_authenticated/admin/website/featured': typeof AuthenticatedAdminWebsiteFeaturedRoute
  '/_authenticated/admin/website/footer': typeof AuthenticatedAdminWebsiteFooterRoute
  '/_authenticated/admin/website/gallery': typeof AuthenticatedAdminWebsiteGalleryRoute
  '/_authenticated/admin/website/hero': typeof AuthenticatedAdminWebsiteHeroRoute
  '/_authenticated/admin/website/nav': typeof AuthenticatedAdminWebsiteNavRoute
  '/_authenticated/portal/academy/$slug': typeof AuthenticatedPortalAcademySlugRoute
  '/_authenticated/admin/website/': typeof AuthenticatedAdminWebsiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/chapters'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/initiatives'
    | '/leadership'
    | '/magazine'
    | '/membership'
    | '/news'
    | '/partners'
    | '/podcasts'
    | '/sitemap.xml'
    | '/admin'
    | '/portal'
    | '/chapters/$slug'
    | '/admin/academy'
    | '/admin/academy-modules'
    | '/admin/chapters'
    | '/admin/enquiries'
    | '/admin/events'
    | '/admin/initiatives'
    | '/admin/leadership'
    | '/admin/magazine'
    | '/admin/members'
    | '/admin/news'
    | '/admin/partners'
    | '/admin/podcasts'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/tiers'
    | '/admin/website'
    | '/portal/academy'
    | '/portal/events'
    | '/portal/magazine'
    | '/portal/membership'
    | '/portal/news'
    | '/portal/podcasts'
    | '/portal/profile'
    | '/admin/'
    | '/portal/'
    | '/admin/website/banner'
    | '/admin/website/chapters'
    | '/admin/website/contact'
    | '/admin/website/featured'
    | '/admin/website/footer'
    | '/admin/website/gallery'
    | '/admin/website/hero'
    | '/admin/website/nav'
    | '/portal/academy/$slug'
    | '/admin/website/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/chapters'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/initiatives'
    | '/leadership'
    | '/magazine'
    | '/membership'
    | '/news'
    | '/partners'
    | '/podcasts'
    | '/sitemap.xml'
    | '/chapters/$slug'
    | '/admin/academy'
    | '/admin/academy-modules'
    | '/admin/chapters'
    | '/admin/enquiries'
    | '/admin/events'
    | '/admin/initiatives'
    | '/admin/leadership'
    | '/admin/magazine'
    | '/admin/members'
    | '/admin/news'
    | '/admin/partners'
    | '/admin/podcasts'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/tiers'
    | '/portal/academy'
    | '/portal/events'
    | '/portal/magazine'
    | '/portal/membership'
    | '/portal/news'
    | '/portal/podcasts'
    | '/portal/profile'
    | '/admin'
    | '/portal'
    | '/admin/website/banner'
    | '/admin/website/chapters'
    | '/admin/website/contact'
    | '/admin/website/featured'
    | '/admin/website/footer'
    | '/admin/website/gallery'
    | '/admin/website/hero'
    | '/admin/website/nav'
    | '/portal/academy/$slug'
    | '/admin/website'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/academy'
    | '/auth'
    | '/chapters'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/initiatives'
    | '/leadership'
    | '/magazine'
    | '/membership'
    | '/news'
    | '/partners'
    | '/podcasts'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/chapters/$slug'
    | '/_authenticated/admin/academy'
    | '/_authenticated/admin/academy-modules'
    | '/_authenticated/admin/chapters'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/initiatives'
    | '/_authenticated/admin/leadership'
    | '/_authenticated/admin/magazine'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/podcasts'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/tiers'
    | '/_authenticated/admin/website'
    | '/_authenticated/portal/academy'
    | '/_authenticated/portal/events'
    | '/_authenticated/portal/magazine'
    | '/_authenticated/portal/membership'
    | '/_authenticated/portal/news'
    | '/_authenticated/portal/podcasts'
    | '/_authenticated/portal/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/website/banner'
    | '/_authenticated/admin/website/chapters'
    | '/_authenticated/admin/website/contact'
    | '/_authenticated/admin/website/featured'
    | '/_authenticated/admin/website/footer'
    | '/_authenticated/admin/website/gallery'
    | '/_authenticated/admin/website/hero'
    | '/_authenticated/admin/website/nav'
    | '/_authenticated/portal/academy/$slug'
    | '/_authenticated/admin/website/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AuthRoute: typeof AuthRoute
  ChaptersRoute: typeof ChaptersRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  InitiativesRoute: typeof InitiativesRoute
  LeadershipRoute: typeof LeadershipRoute
  MagazineRoute: typeof MagazineRoute
  MembershipRoute: typeof MembershipRoute
  NewsRoute: typeof NewsRoute
  PartnersRoute: typeof PartnersRoute
  PodcastsRoute: typeof PodcastsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives': {
      id: '/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof InitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/profile': {
      id: '/_authenticated/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/podcasts': {
      id: '/_authenticated/portal/podcasts'
      path: '/podcasts'
      fullPath: '/portal/podcasts'
      preLoaderRoute: typeof AuthenticatedPortalPodcastsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/news': {
      id: '/_authenticated/portal/news'
      path: '/news'
      fullPath: '/portal/news'
      preLoaderRoute: typeof AuthenticatedPortalNewsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/membership': {
      id: '/_authenticated/portal/membership'
      path: '/membership'
      fullPath: '/portal/membership'
      preLoaderRoute: typeof AuthenticatedPortalMembershipRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/magazine': {
      id: '/_authenticated/portal/magazine'
      path: '/magazine'
      fullPath: '/portal/magazine'
      preLoaderRoute: typeof AuthenticatedPortalMagazineRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/events': {
      id: '/_authenticated/portal/events'
      path: '/events'
      fullPath: '/portal/events'
      preLoaderRoute: typeof AuthenticatedPortalEventsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/academy': {
      id: '/_authenticated/portal/academy'
      path: '/academy'
      fullPath: '/portal/academy'
      preLoaderRoute: typeof AuthenticatedPortalAcademyRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/website': {
      id: '/_authenticated/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tiers': {
      id: '/_authenticated/admin/tiers'
      path: '/tiers'
      fullPath: '/admin/tiers'
      preLoaderRoute: typeof AuthenticatedAdminTiersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/podcasts': {
      id: '/_authenticated/admin/podcasts'
      path: '/podcasts'
      fullPath: '/admin/podcasts'
      preLoaderRoute: typeof AuthenticatedAdminPodcastsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/magazine': {
      id: '/_authenticated/admin/magazine'
      path: '/magazine'
      fullPath: '/admin/magazine'
      preLoaderRoute: typeof AuthenticatedAdminMagazineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leadership': {
      id: '/_authenticated/admin/leadership'
      path: '/leadership'
      fullPath: '/admin/leadership'
      preLoaderRoute: typeof AuthenticatedAdminLeadershipRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/initiatives': {
      id: '/_authenticated/admin/initiatives'
      path: '/initiatives'
      fullPath: '/admin/initiatives'
      preLoaderRoute: typeof AuthenticatedAdminInitiativesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chapters': {
      id: '/_authenticated/admin/chapters'
      path: '/chapters'
      fullPath: '/admin/chapters'
      preLoaderRoute: typeof AuthenticatedAdminChaptersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/academy-modules': {
      id: '/_authenticated/admin/academy-modules'
      path: '/academy-modules'
      fullPath: '/admin/academy-modules'
      preLoaderRoute: typeof AuthenticatedAdminAcademyModulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/academy': {
      id: '/_authenticated/admin/academy'
      path: '/academy'
      fullPath: '/admin/academy'
      preLoaderRoute: typeof AuthenticatedAdminAcademyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/': {
      id: '/_authenticated/admin/website/'
      path: '/'
      fullPath: '/admin/website/'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteIndexRouteImport
      parentRoute: typeof AuthenticatedAdminWebsiteRoute
    }
    '/_authenticated/portal/academy/$slug': {
      id: '/_authenticated/portal/academy/$slug'
      path: '/$slug'
      fullPath: '/portal/academy/$slug'
      preLoaderRoute: typeof AuthenticatedPortalAcademySlugRouteImport
      parentRoute: typeof AuthenticatedPortalAcademyRoute
    }
    '/_authenticated/admin/website/nav': {
      id: '/_authenticated/admin/website/nav'
      path: '/nav'
      fullPath: '/admin/website/nav'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteNavRouteImport
      parentRoute: typeof AuthenticatedAdminWebsiteRoute
    }
    '/_authenticated/admin/website/hero': {
      id: '/_authenticated/admin/website/hero'
      path: '/hero'
      fullPath: '/admin/website/hero'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteHeroRouteImport
      parentRoute: typeof AuthenticatedAdminWebsiteRoute
    }
    '/_authenticated/admin/website/gallery': {
      id: '/_authenticated/admin/website/gallery'
      path: '/gallery'
      fullPath: '/admin/website/gallery'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminWebsiteRoute
    }
    '/_authenticated/admin/website/footer': {
      id: '/_authenticated/admin/website/footer'
      path: '/footer'
      fullPath: '/admin/website/footer'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteFooterRouteImport
      parentRoute: typeof AuthenticatedAdminWebsiteRoute
    }
    '/_authenticated/admin/website/featured': {
      id: '/_authenticated/admin/website/featured'
      path: '/featured'
      fullPath: '/admin/website/featured'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteFeaturedRouteImport
      parentRoute: typeof AuthenticatedAdminWebsiteRoute
    }
    '/_authenticated/admin/website/contact': {
      id: '/_authenticated/admin/website/contact'
      path: '/contact'
      fullPath: '/admin/website/contact'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteContactRouteImport
      parentRoute: typeof AuthenticatedAdminWebsiteRoute
    }
    '/_authenticated/admin/website/chapters': {
      id: '/_authenticated/admin/website/chapters'
      path: '/chapters'
      fullPath: '/admin/website/chapters'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteChaptersRouteImport
      parentRoute: typeof AuthenticatedAdminWebsiteRoute
    }
    '/_authenticated/admin/website/banner': {
      id: '/_authenticated/admin/website/banner'
      path: '/banner'
      fullPath: '/admin/website/banner'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteBannerRouteImport
      parentRoute: typeof AuthenticatedAdminWebsiteRoute
    }
  }
}

interface AuthenticatedAdminWebsiteRouteChildren {
  AuthenticatedAdminWebsiteBannerRoute: typeof AuthenticatedAdminWebsiteBannerRoute
  AuthenticatedAdminWebsiteChaptersRoute: typeof AuthenticatedAdminWebsiteChaptersRoute
  AuthenticatedAdminWebsiteContactRoute: typeof AuthenticatedAdminWebsiteContactRoute
  AuthenticatedAdminWebsiteFeaturedRoute: typeof AuthenticatedAdminWebsiteFeaturedRoute
  AuthenticatedAdminWebsiteFooterRoute: typeof AuthenticatedAdminWebsiteFooterRoute
  AuthenticatedAdminWebsiteGalleryRoute: typeof AuthenticatedAdminWebsiteGalleryRoute
  AuthenticatedAdminWebsiteHeroRoute: typeof AuthenticatedAdminWebsiteHeroRoute
  AuthenticatedAdminWebsiteNavRoute: typeof AuthenticatedAdminWebsiteNavRoute
  AuthenticatedAdminWebsiteIndexRoute: typeof AuthenticatedAdminWebsiteIndexRoute
}

const AuthenticatedAdminWebsiteRouteChildren: AuthenticatedAdminWebsiteRouteChildren =
  {
    AuthenticatedAdminWebsiteBannerRoute: AuthenticatedAdminWebsiteBannerRoute,
    AuthenticatedAdminWebsiteChaptersRoute:
      AuthenticatedAdminWebsiteChaptersRoute,
    AuthenticatedAdminWebsiteContactRoute:
      AuthenticatedAdminWebsiteContactRoute,
    AuthenticatedAdminWebsiteFeaturedRoute:
      AuthenticatedAdminWebsiteFeaturedRoute,
    AuthenticatedAdminWebsiteFooterRoute: AuthenticatedAdminWebsiteFooterRoute,
    AuthenticatedAdminWebsiteGalleryRoute:
      AuthenticatedAdminWebsiteGalleryRoute,
    AuthenticatedAdminWebsiteHeroRoute: AuthenticatedAdminWebsiteHeroRoute,
    AuthenticatedAdminWebsiteNavRoute: AuthenticatedAdminWebsiteNavRoute,
    AuthenticatedAdminWebsiteIndexRoute: AuthenticatedAdminWebsiteIndexRoute,
  }

const AuthenticatedAdminWebsiteRouteWithChildren =
  AuthenticatedAdminWebsiteRoute._addFileChildren(
    AuthenticatedAdminWebsiteRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcademyRoute: typeof AuthenticatedAdminAcademyRoute
  AuthenticatedAdminAcademyModulesRoute: typeof AuthenticatedAdminAcademyModulesRoute
  AuthenticatedAdminChaptersRoute: typeof AuthenticatedAdminChaptersRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminInitiativesRoute: typeof AuthenticatedAdminInitiativesRoute
  AuthenticatedAdminLeadershipRoute: typeof AuthenticatedAdminLeadershipRoute
  AuthenticatedAdminMagazineRoute: typeof AuthenticatedAdminMagazineRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminPodcastsRoute: typeof AuthenticatedAdminPodcastsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminTiersRoute: typeof AuthenticatedAdminTiersRoute
  AuthenticatedAdminWebsiteRoute: typeof AuthenticatedAdminWebsiteRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcademyRoute: AuthenticatedAdminAcademyRoute,
  AuthenticatedAdminAcademyModulesRoute: AuthenticatedAdminAcademyModulesRoute,
  AuthenticatedAdminChaptersRoute: AuthenticatedAdminChaptersRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminInitiativesRoute: AuthenticatedAdminInitiativesRoute,
  AuthenticatedAdminLeadershipRoute: AuthenticatedAdminLeadershipRoute,
  AuthenticatedAdminMagazineRoute: AuthenticatedAdminMagazineRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminPodcastsRoute: AuthenticatedAdminPodcastsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminTiersRoute: AuthenticatedAdminTiersRoute,
  AuthenticatedAdminWebsiteRoute: AuthenticatedAdminWebsiteRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalAcademyRouteChildren {
  AuthenticatedPortalAcademySlugRoute: typeof AuthenticatedPortalAcademySlugRoute
}

const AuthenticatedPortalAcademyRouteChildren: AuthenticatedPortalAcademyRouteChildren =
  {
    AuthenticatedPortalAcademySlugRoute: AuthenticatedPortalAcademySlugRoute,
  }

const AuthenticatedPortalAcademyRouteWithChildren =
  AuthenticatedPortalAcademyRoute._addFileChildren(
    AuthenticatedPortalAcademyRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAcademyRoute: typeof AuthenticatedPortalAcademyRouteWithChildren
  AuthenticatedPortalEventsRoute: typeof AuthenticatedPortalEventsRoute
  AuthenticatedPortalMagazineRoute: typeof AuthenticatedPortalMagazineRoute
  AuthenticatedPortalMembershipRoute: typeof AuthenticatedPortalMembershipRoute
  AuthenticatedPortalNewsRoute: typeof AuthenticatedPortalNewsRoute
  AuthenticatedPortalPodcastsRoute: typeof AuthenticatedPortalPodcastsRoute
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAcademyRoute: AuthenticatedPortalAcademyRouteWithChildren,
  AuthenticatedPortalEventsRoute: AuthenticatedPortalEventsRoute,
  AuthenticatedPortalMagazineRoute: AuthenticatedPortalMagazineRoute,
  AuthenticatedPortalMembershipRoute: AuthenticatedPortalMembershipRoute,
  AuthenticatedPortalNewsRoute: AuthenticatedPortalNewsRoute,
  AuthenticatedPortalPodcastsRoute: AuthenticatedPortalPodcastsRoute,
  AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ChaptersRouteChildren {
  ChaptersSlugRoute: typeof ChaptersSlugRoute
}

const ChaptersRouteChildren: ChaptersRouteChildren = {
  ChaptersSlugRoute: ChaptersSlugRoute,
}

const ChaptersRouteWithChildren = ChaptersRoute._addFileChildren(
  ChaptersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AuthRoute: AuthRoute,
  ChaptersRoute: ChaptersRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  InitiativesRoute: InitiativesRoute,
  LeadershipRoute: LeadershipRoute,
  MagazineRoute: MagazineRoute,
  MembershipRoute: MembershipRoute,
  NewsRoute: NewsRoute,
  PartnersRoute: PartnersRoute,
  PodcastsRoute: PodcastsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
