GRANT SELECT, INSERT, UPDATE, DELETE ON public.academy_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.academy_lessons TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.academy_modules TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.banners TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.certificates TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chapters TO authenticated;
GRANT SELECT ON public.contact_messages TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.content_access TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.events TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.featured_images TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gallery_images TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.initiatives TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.leadership TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.magazine_articles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.magazine_issues TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.member_course_progress TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.members TO authenticated;
GRANT SELECT ON public.membership_enquiries TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.membership_tiers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.nav_links TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.news TO authenticated;
GRANT SELECT ON public.newsletter_subs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.partners TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.podcast_episodes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.site_settings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.testimonials TO authenticated;
GRANT SELECT ON public.user_roles TO authenticated;

GRANT ALL ON public.academy_items TO service_role;
GRANT ALL ON public.academy_lessons TO service_role;
GRANT ALL ON public.academy_modules TO service_role;
GRANT ALL ON public.banners TO service_role;
GRANT ALL ON public.certificates TO service_role;
GRANT ALL ON public.chapters TO service_role;
GRANT ALL ON public.contact_messages TO service_role;
GRANT ALL ON public.content_access TO service_role;
GRANT ALL ON public.events TO service_role;
GRANT ALL ON public.featured_images TO service_role;
GRANT ALL ON public.gallery_images TO service_role;
GRANT ALL ON public.initiatives TO service_role;
GRANT ALL ON public.leadership TO service_role;
GRANT ALL ON public.magazine_articles TO service_role;
GRANT ALL ON public.magazine_issues TO service_role;
GRANT ALL ON public.member_course_progress TO service_role;
GRANT ALL ON public.members TO service_role;
GRANT ALL ON public.membership_enquiries TO service_role;
GRANT ALL ON public.membership_tiers TO service_role;
GRANT ALL ON public.nav_links TO service_role;
GRANT ALL ON public.news TO service_role;
GRANT ALL ON public.newsletter_subs TO service_role;
GRANT ALL ON public.partners TO service_role;
GRANT ALL ON public.podcast_episodes TO service_role;
GRANT ALL ON public.site_settings TO service_role;
GRANT ALL ON public.testimonials TO service_role;
GRANT ALL ON public.user_roles TO service_role;

GRANT SELECT ON public.banners TO anon;
GRANT SELECT ON public.featured_images TO anon;
GRANT SELECT ON public.gallery_images TO anon;
GRANT SELECT ON public.magazine_articles TO anon;
GRANT SELECT ON public.magazine_issues TO anon;
GRANT SELECT ON public.membership_tiers TO anon;
GRANT SELECT ON public.nav_links TO anon;
GRANT SELECT ON public.podcast_episodes TO anon;